// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace StringManager.API.Specs.Features.UserManagement
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UserManagementCreateUserFeature : object, Xunit.IClassFixture<UserManagementCreateUserFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateUser.feature"
#line hidden
        
        public UserManagementCreateUserFeature(UserManagementCreateUserFeature.FixtureData fixtureData, StringManager_API_Specs_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/UserManagement", "UserManagement/CreateUser", "Note: Improve the SuperUser handling\nMaybe it could be divided up into a role or " +
                    "tag functionallity where the first user created is an Administrator\nAfter that i" +
                    "t is possible to select the role for the user\n- Administrator\n- UserAdmin\n- Fold" +
                    "erAdmin\n- User", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 10
   #line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserId",
                        "Email",
                        "UserRole",
                        "Password"});
            table39.AddRow(new string[] {
                        "616aba5c-e933-4b22-a383-93aea94379b4",
                        "adminuser@email.com",
                        "Administrator",
                        "Password1"});
            table39.AddRow(new string[] {
                        "c0a1b5bd-d48d-44c3-bf25-0500ebbd239d",
                        "useradmin@email.com",
                        "UserAdmin",
                        "Password2"});
            table39.AddRow(new string[] {
                        "910b77cb-ee2a-4673-bc34-78c0992b0f05",
                        "folderadmin@email.com",
                        "FolderAdmin",
                        "Password3"});
            table39.AddRow(new string[] {
                        "11a8f678-b1b4-4d95-8191-0ea27f72407e",
                        "user@email.com",
                        "User",
                        "Password4"});
#line 11
      testRunner.Given("that the following users exists", ((string)(null)), table39, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserId",
                        "RoleType"});
            table40.AddRow(new string[] {
                        "616aba5c-e933-4b22-a383-93aea94379b4",
                        "Administrator"});
            table40.AddRow(new string[] {
                        "c0a1b5bd-d48d-44c3-bf25-0500ebbd239d",
                        "UserAdmin"});
            table40.AddRow(new string[] {
                        "910b77cb-ee2a-4673-bc34-78c0992b0f05",
                        "FolderAdmin"});
#line 17
      testRunner.And("that the users have the following roles", ((string)(null)), table40, "And ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "AccessGroupId",
                        "AccessGroupName"});
            table41.AddRow(new string[] {
                        "4605a27b-6f86-47c3-ac1a-547aa1b01fe3",
                        "Marketing"});
            table41.AddRow(new string[] {
                        "ec77e8bf-f31b-411b-8942-6cfcce1266e7",
                        "Sales"});
#line 22
      testRunner.And("that the following access groups exists", ((string)(null)), table41, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="User with user management role or administrator creates new standard user")]
        [Xunit.TraitAttribute("FeatureTitle", "UserManagement/CreateUser")]
        [Xunit.TraitAttribute("Description", "User with user management role or administrator creates new standard user")]
        [Xunit.TraitAttribute("Category", "ResourceCreation")]
        [Xunit.InlineDataAttribute("adminuser@email.com", "Password1", new string[0])]
        [Xunit.InlineDataAttribute("useradmin@email.com", "Password2", new string[0])]
        public void UserWithUserManagementRoleOrAdministratorCreatesNewStandardUser(string email, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ResourceCreation"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("password", password);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User with user management role or administrator creates new standard user", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
   this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table42.AddRow(new string[] {
                            string.Format("{0}", email),
                            string.Format("{0}", password)});
#line 29
      testRunner.Given("that the user signs in with the following information", ((string)(null)), table42, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RoleType"});
                table43.AddRow(new string[] {
                            "testuser@email.com",
                            "Abcdefg123",
                            "User"});
#line 32
      testRunner.And("want to create a new user with the following information", ((string)(null)), table43, "And ");
#line hidden
                TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccessGroupId"});
                table44.AddRow(new string[] {
                            "4605a27b-6f86-47c3-ac1a-547aa1b01fe3"});
                table44.AddRow(new string[] {
                            "ec77e8bf-f31b-411b-8942-6cfcce1266e7"});
#line 35
      testRunner.And("that the new user should be included in the following access groups", ((string)(null)), table44, "And ");
#line hidden
#line 39
      testRunner.When("the new user request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 40
      testRunner.Then("the new user is created with the expected information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
      testRunner.And("the new users id is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 42
      testRunner.And("the http status code \"201 Created\" is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Administrator tries to create new user with Administrator role")]
        [Xunit.TraitAttribute("FeatureTitle", "UserManagement/CreateUser")]
        [Xunit.TraitAttribute("Description", "Administrator tries to create new user with Administrator role")]
        [Xunit.TraitAttribute("Category", "ResourceCreation")]
        public void AdministratorTriesToCreateNewUserWithAdministratorRole()
        {
            string[] tagsOfScenario = new string[] {
                    "ResourceCreation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Administrator tries to create new user with Administrator role", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
   this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table45.AddRow(new string[] {
                            "adminuser@email.com",
                            "Password1"});
#line 52
      testRunner.Given("that the user signs in with the following information", ((string)(null)), table45, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RoleType"});
                table46.AddRow(new string[] {
                            "testuser@email.com",
                            "abc123",
                            "Administrator"});
#line 55
      testRunner.And("want to create a new user with the following information", ((string)(null)), table46, "And ");
#line hidden
#line 58
      testRunner.When("the new user request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 59
      testRunner.Then("the new user is created with the expected information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 60
      testRunner.And("the new users id is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 61
      testRunner.And("the http status code \"201 Created\" is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Administrator tries to create new user with UserAdmin role")]
        [Xunit.TraitAttribute("FeatureTitle", "UserManagement/CreateUser")]
        [Xunit.TraitAttribute("Description", "Administrator tries to create new user with UserAdmin role")]
        [Xunit.TraitAttribute("Category", "ResourceCreation")]
        public void AdministratorTriesToCreateNewUserWithUserAdminRole()
        {
            string[] tagsOfScenario = new string[] {
                    "ResourceCreation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Administrator tries to create new user with UserAdmin role", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
   this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table47.AddRow(new string[] {
                            "adminuser@email.com",
                            "Password1"});
#line 65
      testRunner.Given("that the user signs in with the following information", ((string)(null)), table47, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table48 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RoleType"});
                table48.AddRow(new string[] {
                            "testuser@email.com",
                            "abc123",
                            "UserAdmin"});
#line 68
      testRunner.And("want to create a new user with the following information", ((string)(null)), table48, "And ");
#line hidden
                TechTalk.SpecFlow.Table table49 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccessGroupId"});
                table49.AddRow(new string[] {
                            "4605a27b-6f86-47c3-ac1a-547aa1b01fe3"});
                table49.AddRow(new string[] {
                            "ec77e8bf-f31b-411b-8942-6cfcce1266e7"});
#line 71
      testRunner.And("that the new user should be included in the following access groups", ((string)(null)), table49, "And ");
#line hidden
#line 75
      testRunner.When("the new user request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 76
      testRunner.Then("the new user is created with the expected information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 77
      testRunner.And("the new users id is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 78
      testRunner.And("the http status code \"201 Created\" is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="User admin tries to create new user with UserAdmin role")]
        [Xunit.TraitAttribute("FeatureTitle", "UserManagement/CreateUser")]
        [Xunit.TraitAttribute("Description", "User admin tries to create new user with UserAdmin role")]
        [Xunit.TraitAttribute("Category", "ResourceCreation")]
        public void UserAdminTriesToCreateNewUserWithUserAdminRole()
        {
            string[] tagsOfScenario = new string[] {
                    "ResourceCreation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User admin tries to create new user with UserAdmin role", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 81
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
   this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table50 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table50.AddRow(new string[] {
                            "useradmin@email.com",
                            "Password2"});
#line 82
      testRunner.Given("that the user signs in with the following information", ((string)(null)), table50, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table51 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RoleType"});
                table51.AddRow(new string[] {
                            "testuser@email.com",
                            "abc123",
                            "UserAdmin"});
#line 85
      testRunner.And("want to create a new user with the following information", ((string)(null)), table51, "And ");
#line hidden
                TechTalk.SpecFlow.Table table52 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccessGroupId"});
                table52.AddRow(new string[] {
                            "4605a27b-6f86-47c3-ac1a-547aa1b01fe3"});
                table52.AddRow(new string[] {
                            "ec77e8bf-f31b-411b-8942-6cfcce1266e7"});
#line 88
      testRunner.And("that the new user should be included in the following access groups", ((string)(null)), table52, "And ");
#line hidden
#line 92
      testRunner.When("the new user request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 93
      testRunner.Then("the new user is created with the expected information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 94
      testRunner.And("the new users id is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 95
      testRunner.And("the http status code \"201 Created\" is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="User admin tries to create new user with FolderAdmin role")]
        [Xunit.TraitAttribute("FeatureTitle", "UserManagement/CreateUser")]
        [Xunit.TraitAttribute("Description", "User admin tries to create new user with FolderAdmin role")]
        [Xunit.TraitAttribute("Category", "ResourceCreation")]
        public void UserAdminTriesToCreateNewUserWithFolderAdminRole()
        {
            string[] tagsOfScenario = new string[] {
                    "ResourceCreation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User admin tries to create new user with FolderAdmin role", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 98
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
   this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table53 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table53.AddRow(new string[] {
                            "useradmin@email.com",
                            "Password2"});
#line 99
      testRunner.Given("that the user signs in with the following information", ((string)(null)), table53, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table54 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RoleType"});
                table54.AddRow(new string[] {
                            "testuser@email.com",
                            "abc123",
                            "FolderAdmin"});
#line 102
      testRunner.And("want to create a new user with the following information", ((string)(null)), table54, "And ");
#line hidden
#line 105
      testRunner.When("the new user request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 106
      testRunner.Then("the new user is created with the expected information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 107
      testRunner.And("the new users id is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 108
      testRunner.And("the http status code \"201 Created\" is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="User admin tries to create new administrator")]
        [Xunit.TraitAttribute("FeatureTitle", "UserManagement/CreateUser")]
        [Xunit.TraitAttribute("Description", "User admin tries to create new administrator")]
        [Xunit.TraitAttribute("Category", "BusinessRuleError")]
        public void UserAdminTriesToCreateNewAdministrator()
        {
            string[] tagsOfScenario = new string[] {
                    "BusinessRuleError"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User admin tries to create new administrator", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 111
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
   this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table55 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table55.AddRow(new string[] {
                            "useradmin@email.com",
                            "Password2"});
#line 112
      testRunner.Given("that the user signs in with the following information", ((string)(null)), table55, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table56 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RoleType"});
                table56.AddRow(new string[] {
                            "testuser@email.com",
                            "abc123",
                            "Administrator"});
#line 115
      testRunner.And("want to create a new user with the following information", ((string)(null)), table56, "And ");
#line hidden
                TechTalk.SpecFlow.Table table57 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccessGroupId"});
                table57.AddRow(new string[] {
                            "4605a27b-6f86-47c3-ac1a-547aa1b01fe3"});
                table57.AddRow(new string[] {
                            "ec77e8bf-f31b-411b-8942-6cfcce1266e7"});
#line 118
      testRunner.And("that the new user should be included in the following access groups", ((string)(null)), table57, "And ");
#line hidden
#line 122
      testRunner.When("the new user request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 123
      testRunner.Then("a new user is not created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 124
      testRunner.And("the http status code \"400 Bad Request\" is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table58 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProblemType",
                            "Title",
                            "Detail",
                            "HttpStatus"});
                table58.AddRow(new string[] {
                            "UnauthorizedRoleAssignment",
                            "Insufficient permissions",
                            "You can not create a new user with the role that you selected.",
                            "400"});
#line 125
      testRunner.And("the following problem detail is returned", ((string)(null)), table58, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Folder admin tries to create new user")]
        [Xunit.TraitAttribute("FeatureTitle", "UserManagement/CreateUser")]
        [Xunit.TraitAttribute("Description", "Folder admin tries to create new user")]
        [Xunit.TraitAttribute("Category", "BusinessRuleError")]
        public void FolderAdminTriesToCreateNewUser()
        {
            string[] tagsOfScenario = new string[] {
                    "BusinessRuleError"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Folder admin tries to create new user", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 130
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
   this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table59 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table59.AddRow(new string[] {
                            "folderadmin@email.com",
                            "Password3"});
#line 131
      testRunner.Given("that the user signs in with the following information", ((string)(null)), table59, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table60 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RoleType"});
                table60.AddRow(new string[] {
                            "testuser@email.com",
                            "abc123",
                            "User"});
#line 134
      testRunner.And("want to create a new user with the following information", ((string)(null)), table60, "And ");
#line hidden
                TechTalk.SpecFlow.Table table61 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccessGroupId"});
                table61.AddRow(new string[] {
                            "4605a27b-6f86-47c3-ac1a-547aa1b01fe3"});
                table61.AddRow(new string[] {
                            "ec77e8bf-f31b-411b-8942-6cfcce1266e7"});
#line 137
      testRunner.And("that the new user should be included in the following access groups", ((string)(null)), table61, "And ");
#line hidden
#line 141
      testRunner.When("the new user request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 142
      testRunner.Then("a new user is not created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 143
      testRunner.And("the http status code \"400 Bad Request\" is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table62 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProblemType",
                            "Title",
                            "Detail",
                            "HttpStatus"});
                table62.AddRow(new string[] {
                            "InsufficientPermissions",
                            "Insufficient permissions",
                            "You can not create a new user.",
                            "400"});
#line 144
      testRunner.And("the following problem detail is returned", ((string)(null)), table62, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Administrator tries to create a new user with an email that is already registered" +
            "")]
        [Xunit.TraitAttribute("FeatureTitle", "UserManagement/CreateUser")]
        [Xunit.TraitAttribute("Description", "Administrator tries to create a new user with an email that is already registered" +
            "")]
        [Xunit.TraitAttribute("Category", "BusinessRuleError")]
        public void AdministratorTriesToCreateANewUserWithAnEmailThatIsAlreadyRegistered()
        {
            string[] tagsOfScenario = new string[] {
                    "BusinessRuleError"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Administrator tries to create a new user with an email that is already registered" +
                    "", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 149
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
   this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table63 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table63.AddRow(new string[] {
                            "adminuser@email.com",
                            "Password1"});
#line 150
      testRunner.Given("that the user signs in with the following information", ((string)(null)), table63, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table64 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RoleType"});
                table64.AddRow(new string[] {
                            "folderadmin@email.com",
                            "abc123",
                            "User"});
#line 153
      testRunner.And("want to create a new user with the following information", ((string)(null)), table64, "And ");
#line hidden
                TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccessGroupId"});
                table65.AddRow(new string[] {
                            "4605a27b-6f86-47c3-ac1a-547aa1b01fe3"});
                table65.AddRow(new string[] {
                            "ec77e8bf-f31b-411b-8942-6cfcce1266e7"});
#line 156
      testRunner.And("that the new user should be included in the following access groups", ((string)(null)), table65, "And ");
#line hidden
#line 160
      testRunner.When("the new user request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 161
      testRunner.Then("a new user is not created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 162
      testRunner.And("the http status code \"400 Bad Request\" is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table66 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProblemType",
                            "Title",
                            "Detail",
                            "HttpStatus"});
                table66.AddRow(new string[] {
                            "ExistingEmail",
                            "Existing email",
                            "The email entered for the new user is already registered.",
                            "400"});
#line 163
      testRunner.And("the following problem detail is returned", ((string)(null)), table66, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Administrator tries to create a new user with an invalid email")]
        [Xunit.TraitAttribute("FeatureTitle", "UserManagement/CreateUser")]
        [Xunit.TraitAttribute("Description", "Administrator tries to create a new user with an invalid email")]
        [Xunit.TraitAttribute("Category", "BusinessRuleError")]
        [Xunit.InlineDataAttribute("hello", new string[0])]
        [Xunit.InlineDataAttribute("123", new string[0])]
        [Xunit.InlineDataAttribute("<NULL />", new string[0])]
        [Xunit.InlineDataAttribute("<EMPTY />", new string[0])]
        [Xunit.InlineDataAttribute("email@com", new string[0])]
        [Xunit.InlineDataAttribute("email@.com", new string[0])]
        [Xunit.InlineDataAttribute("@server.com", new string[0])]
        public void AdministratorTriesToCreateANewUserWithAnInvalidEmail(string invalidEmail, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "BusinessRuleError"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("invalidEmail", invalidEmail);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Administrator tries to create a new user with an invalid email", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 168
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
   this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table67 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table67.AddRow(new string[] {
                            "adminuser@email.com",
                            "Password1"});
#line 169
      testRunner.Given("that the user signs in with the following information", ((string)(null)), table67, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table68 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RoleType"});
                table68.AddRow(new string[] {
                            string.Format("{0}", invalidEmail),
                            "abc123",
                            "User"});
#line 172
      testRunner.And("want to create a new user with the following information", ((string)(null)), table68, "And ");
#line hidden
                TechTalk.SpecFlow.Table table69 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccessGroupId"});
                table69.AddRow(new string[] {
                            "4605a27b-6f86-47c3-ac1a-547aa1b01fe3"});
                table69.AddRow(new string[] {
                            "ec77e8bf-f31b-411b-8942-6cfcce1266e7"});
#line 175
      testRunner.And("that the new user should be included in the following access groups", ((string)(null)), table69, "And ");
#line hidden
#line 179
      testRunner.When("the new user request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 180
      testRunner.Then("a new user is not created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 181
      testRunner.And("the http status code \"400 Bad Request\" is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table70 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProblemType",
                            "Title",
                            "Detail",
                            "HttpStatus"});
                table70.AddRow(new string[] {
                            "InvalidEmail",
                            "Invalid email",
                            "The email entered for the new user is invalid.",
                            "400"});
#line 182
      testRunner.And("the following problem detail is returned", ((string)(null)), table70, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Administrator tries to create a new user with invalid password")]
        [Xunit.TraitAttribute("FeatureTitle", "UserManagement/CreateUser")]
        [Xunit.TraitAttribute("Description", "Administrator tries to create a new user with invalid password")]
        [Xunit.TraitAttribute("Category", "BusinessRuleError")]
        [Xunit.InlineDataAttribute("hello", new string[0])]
        [Xunit.InlineDataAttribute("123", new string[0])]
        [Xunit.InlineDataAttribute("<NULL />", new string[0])]
        [Xunit.InlineDataAttribute("<EMPTY />", new string[0])]
        [Xunit.InlineDataAttribute("qwerty1", new string[0])]
        [Xunit.InlineDataAttribute("qwerty123!", new string[0])]
        [Xunit.InlineDataAttribute("Qwerty123", new string[0])]
        public void AdministratorTriesToCreateANewUserWithInvalidPassword(string invalidPassword, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "BusinessRuleError"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("invalidPassword", invalidPassword);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Administrator tries to create a new user with invalid password", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 197
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
   this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table71 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table71.AddRow(new string[] {
                            "adminuser@email.com",
                            "Password1"});
#line 198
      testRunner.Given("that the user signs in with the following information", ((string)(null)), table71, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table72 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RoleType"});
                table72.AddRow(new string[] {
                            "test@email.com",
                            string.Format("{0}", invalidPassword),
                            "User"});
#line 201
      testRunner.And("want to create a new user with the following information", ((string)(null)), table72, "And ");
#line hidden
                TechTalk.SpecFlow.Table table73 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccessGroupId"});
                table73.AddRow(new string[] {
                            "4605a27b-6f86-47c3-ac1a-547aa1b01fe3"});
                table73.AddRow(new string[] {
                            "ec77e8bf-f31b-411b-8942-6cfcce1266e7"});
#line 204
      testRunner.And("that the new user should be included in the following access groups", ((string)(null)), table73, "And ");
#line hidden
#line 208
      testRunner.When("the new user request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 209
      testRunner.Then("a new user is not created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 210
      testRunner.And("the http status code \"400 Bad Request\" is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table74 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProblemType",
                            "Title",
                            "Detail",
                            "HttpStatus"});
                table74.AddRow(new string[] {
                            "InvalidPassword",
                            "Invalid password",
                            "The password entered for the new user is invalid.",
                            "400"});
#line 211
      testRunner.And("the following problem detail is returned", ((string)(null)), table74, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Administrator tries to create a new user with initial access group that does not " +
            "exist")]
        [Xunit.TraitAttribute("FeatureTitle", "UserManagement/CreateUser")]
        [Xunit.TraitAttribute("Description", "Administrator tries to create a new user with initial access group that does not " +
            "exist")]
        [Xunit.TraitAttribute("Category", "BusinessRuleError")]
        public void AdministratorTriesToCreateANewUserWithInitialAccessGroupThatDoesNotExist()
        {
            string[] tagsOfScenario = new string[] {
                    "BusinessRuleError"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Administrator tries to create a new user with initial access group that does not " +
                    "exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 226
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
   this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table75 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password"});
                table75.AddRow(new string[] {
                            "adminuser@email.com",
                            "Password1"});
#line 227
      testRunner.Given("that the user signs in with the following information", ((string)(null)), table75, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table76 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RoleType"});
                table76.AddRow(new string[] {
                            "test@email.com",
                            "<invalidPassword>",
                            "User"});
#line 230
      testRunner.And("want to create a new user with the following information", ((string)(null)), table76, "And ");
#line hidden
                TechTalk.SpecFlow.Table table77 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccessGroupId"});
                table77.AddRow(new string[] {
                            "4605a27b-6f86-47c3-ac1a-547aa1b01fe3"});
                table77.AddRow(new string[] {
                            "8c9e47e5-b2ec-4818-8fe8-35241e3d26fb"});
#line 233
      testRunner.And("that the new user should be included in the following access groups", ((string)(null)), table77, "And ");
#line hidden
#line 237
      testRunner.When("the new user request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 238
      testRunner.Then("a new user is not created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 239
      testRunner.And("the http status code \"400 Bad Request\" is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table78 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProblemType",
                            "Title",
                            "Detail",
                            "HttpStatus"});
                table78.AddRow(new string[] {
                            "InvalidAccessGroup",
                            "Invalid access group",
                            "One of the initial access groups added to the user does not exist.",
                            "400"});
#line 240
      testRunner.And("the following problem detail is returned", ((string)(null)), table78, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="User that is not signed in tries to create a new user")]
        [Xunit.TraitAttribute("FeatureTitle", "UserManagement/CreateUser")]
        [Xunit.TraitAttribute("Description", "User that is not signed in tries to create a new user")]
        [Xunit.TraitAttribute("Category", "AuthenticationError")]
        public void UserThatIsNotSignedInTriesToCreateANewUser()
        {
            string[] tagsOfScenario = new string[] {
                    "AuthenticationError"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User that is not signed in tries to create a new user", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 245
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
   this.FeatureBackground();
#line hidden
#line 246
      testRunner.Given("that no user is signed in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table79 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Password",
                            "RoleType"});
                table79.AddRow(new string[] {
                            "test@email.com",
                            "invalidPassword",
                            "User"});
#line 247
      testRunner.And("want to create a new user with the following information", ((string)(null)), table79, "And ");
#line hidden
                TechTalk.SpecFlow.Table table80 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccessGroupId"});
                table80.AddRow(new string[] {
                            "4605a27b-6f86-47c3-ac1a-547aa1b01fe3"});
                table80.AddRow(new string[] {
                            "8c9e47e5-b2ec-4818-8fe8-35241e3d26fb"});
#line 250
      testRunner.And("that the new user should be included in the following access groups", ((string)(null)), table80, "And ");
#line hidden
#line 254
      testRunner.When("the new user request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 255
      testRunner.Then("a new user is not created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 256
      testRunner.And("the http status code \"401 Unauthorized\" is returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table81 = new TechTalk.SpecFlow.Table(new string[] {
                            "ProblemType",
                            "Title",
                            "Detail",
                            "HttpStatus"});
                table81.AddRow(new string[] {
                            "UnauthorizedAction",
                            "Not authorized",
                            "You are not authorized to perform this action.",
                            "401"});
#line 257
      testRunner.And("the following problem detail is returned", ((string)(null)), table81, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                UserManagementCreateUserFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                UserManagementCreateUserFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
