//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringManager.Infrastructure.Services {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProblemDetailTexts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProblemDetailTexts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("StringManager.Infrastructure.Services.ProblemDetailTexts", typeof(ProblemDetailTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string detail_InvalidEmail {
            get {
                return ResourceManager.GetString("detail-InvalidEmail", resourceCulture);
            }
        }
        
        internal static string title_InvalidEmail {
            get {
                return ResourceManager.GetString("title-InvalidEmail", resourceCulture);
            }
        }
        
        internal static string detail_InvalidName {
            get {
                return ResourceManager.GetString("detail-InvalidName", resourceCulture);
            }
        }
        
        internal static string title_InvalidName {
            get {
                return ResourceManager.GetString("title-InvalidName", resourceCulture);
            }
        }
        
        internal static string detail_NoUserFound {
            get {
                return ResourceManager.GetString("detail-NoUserFound", resourceCulture);
            }
        }
        
        internal static string title_NoUserFound {
            get {
                return ResourceManager.GetString("title-NoUserFound", resourceCulture);
            }
        }
        
        internal static string title_IncorrectPassword {
            get {
                return ResourceManager.GetString("title-IncorrectPassword", resourceCulture);
            }
        }
        
        internal static string detail_IncorrectPassword {
            get {
                return ResourceManager.GetString("detail-IncorrectPassword", resourceCulture);
            }
        }
    }
}
